# -*- coding: utf-8 -*-
# cities_data.py — Barboursville: nearby-city landing pages. Edit copy here; build_cities.py renders.
CITY_SITE = {
 "base": "https://barboursville.serenemedspas.com",
 "loc_short": "Barboursville",
 "biz_name": "Serene Med Spa — Barboursville",
 "tel": "tel:+13045200461", "tel_e164": "+1-304-520-0461", "phone": "(304) 520-0461",
 "addr1": "1 Chateau Grove Ln", "addr2": "Barboursville, WV 25504",
 "address": {"@type":"PostalAddress","streetAddress":"1 Chateau Grove Ln","addressLocality":"Barboursville","addressRegion":"WV","postalCode":"25504","addressCountry":"US"},
 "geo": {"@type":"GeoCoordinates","latitude":38.4109,"longitude":-82.2926},
 "geo_meta": '<meta name="geo.region" content="US-WV"><meta name="geo.placename" content="Barboursville, West Virginia"><meta name="geo.position" content="38.4109;-82.2926"><meta name="ICBM" content="38.4109, -82.2926">',
 "dest_q": "1+Chateau+Grove+Ln+Barboursville+WV+25504",
 "hours": "Mon&ndash;Fri: 9 AM &ndash; 5 PM<br>Sat&ndash;Sun: By appointment",
 "hours_spec": [{"@type":"OpeningHoursSpecification","dayOfWeek":["Monday","Tuesday","Wednesday","Thursday","Friday"],"opens":"09:00","closes":"17:00"}],
 "hero_img": "lobby.jpg",
 "ntreat": 39,
 "promo": "",  # NAV already carries the price-match ribbon
 "steps": [
  ("Book online or call", "Choose a free consultation or a specific treatment on our live calendar. If you&rsquo;re driving in from Kentucky or Ohio, tell us and we&rsquo;ll group your visits."),
  ("Exit 20, park at the door", "We&rsquo;re at 1 Chateau Grove Ln, just off I-64 exit 20 (Barboursville / Huntington Mall) on the US-60 side, with free parking outside the door."),
  ("Meet your physician", "Dr. Shweta Arora, Dr. Robin Arora or Stephanie Welker, FNP-BC reviews your goals, skin and history and builds a plan with prices. Most consults take 20&ndash;30 minutes."),
  ("Treat the same day", "Botox, filler, SKINVIVE, SKNLAB and HydraFacial, and most laser treatments can be done at the consult if you&rsquo;re a candidate, so one trip covers both."),
 ],
}

TREATMENTS = [
 ("botox","Botox &amp; Wrinkle Relaxers","$10/unit","Botox, Dysport, Xeomin and Daxxify for frown lines, forehead lines and crow&rsquo;s feet &mdash; physician-injected, price-matched."),
 ("fillers","Dermal Fillers","$500/syringe","The full Juv&eacute;derm family, Restylane and Radiesse for lips, cheeks, jawline, chin and under-eyes. Three Juv&eacute;derm syringes $1,300."),
 ("laser-hair-removal","Laser Hair Removal","Per area","Alma Soprano Ice Platinum &mdash; virtually painless, safe for all skin tones, all year."),
 ("sknlab","SKNLAB Facial","$150","Six-handpiece customized facial &mdash; HydraFacial-style cleansing plus ultrasound, hot/cold, microcurrent and lymphatic drainage. No downtime."),
 ("hydrafacial","HydraFacial","$150","30-minute cleanse, extract and hydrate. Makeup-ready when you leave."),
 ("weight-loss","Medical Weight Loss","$149/visit","Physician-supervised semaglutide and tirzepatide with monthly check-ins."),
 ("alma-hybrid","Alma Hybrid CO&sup2; Resurfacing","From $600","CO2 + 1570 nm fractional resurfacing for texture, scars and sun damage with less downtime."),
 ("kybella","Kybella Double-Chin Treatment","$600/vial","The only FDA-approved injectable that permanently dissolves fat under the chin."),
 ("iv-therapy","IV Therapy &amp; NAD+","From $149","Hydration, immune, energy and NAD+ infusions."),
 ("lip-filler","Lip Filler","$500 (Mini Pout $300)","Natural, proportioned lips with Volbella, Ultra XC or Restylane Kysse."),
 ("sculptra","Sculptra","$600/vial","Collagen stimulator for gradual, natural volume in the face and body."),
 ("hormone-optimization","Bi&ouml;te Hormone Optimization","From $405","Pellet therapy for energy, sleep, mood and libido &mdash; certified Bi&ouml;te providers."),
 ("laser-tattoo-removal","Laser Tattoo Removal","By size","Discovery Pico Plus picosecond laser for full removal or fading before a cover-up."),
]

CITIES = [
 {"slug":"med-spa-huntington-wv","city":"Huntington","city_state":"Huntington, WV","also":["Pea Ridge, WV","Westmoreland, WV","Guyandotte, WV","Ceredo, WV","Kenova, WV"],
  "title":"Med Spa Near Huntington, WV | Botox $10/unit & Fillers",
  "desc":"Huntington's physician-led med spa, 15 min east in Barboursville: Botox $10/unit, Juvéderm fillers $500, laser hair removal, SKNLAB & HydraFacial.",
  "h1":"Huntington&rsquo;s physician-led med spa &mdash; 15 minutes east at exit 20",
  "hero":"Serene Med Spa is where Huntington patients go for doctors who inject, prices posted online, and a Tri-State price match. We&rsquo;re just off I-64 at the Huntington Mall exit in Barboursville, with free parking at the door.",
  "drive":"About 15 minutes",
  "introh2":"Why Huntington drives to Barboursville for Botox and fillers",
  "introlead":"From Marshall, Ritter Park, Southside or Pea Ridge, Serene is a 15-minute trip east on I-64 or US-60 &mdash; and it&rsquo;s one of the very few med spas in the Tri-State owned and run by board-certified physicians who do the treatments themselves.",
  "intro":"<p>Dr. Shweta Arora (board-certified anesthesiologist, certified in aesthetic medicine) and Dr. Robin Arora (board-certified internal medicine and nephrology) see every patient, alongside Stephanie Welker, FNP-BC. We&rsquo;re an <strong>Allergan Platinum</strong> partner, a Merz preferred practice, an Ultherapy PRIME provider, and an Alma and Cartessa device practice &mdash; so the full menu is under one roof.</p><p>Pricing is public and we match it: Botox is $10 per unit, filler is $500 per syringe (three Juv&eacute;derm syringes for $1,300), HydraFacial and the new SKNLAB facial are $150, and every other number is on our <a href=\"/pricing/\">price list</a>. If a Huntington practice publishes a lower price on the same injectable, we&rsquo;ll match it &mdash; see the <a href=\"/#price-match\">Tri-State price match</a>.</p><p>The drive is easy from anywhere in Huntington: I-64 east to exit 20 (Barboursville / Huntington Mall), or US-60 east through Guyandotte and past the mall. We&rsquo;re at 1 Chateau Grove Ln with free parking outside the door. Many patients from Westmoreland, Ceredo and Kenova pair a visit with errands at the mall.</p>",
  "treatments":["botox","fillers","laser-hair-removal","sknlab","weight-loss","alma-hybrid"],
  "directions":"<p><strong>From downtown Huntington (about 10 miles):</strong> take I-64 East to exit 20 (Barboursville / US-60). Follow the signs toward the Huntington Mall; we&rsquo;re at 1 Chateau Grove Ln, just off US-60, about 15 minutes door to door.</p><p><strong>From Pea Ridge / Guyandotte:</strong> US-60 East (Route 60) straight into Barboursville, about 10 minutes. <strong>From Westmoreland, Ceredo or Kenova:</strong> I-64 East to exit 20, about 20&ndash;25 minutes.</p>",
  "origin_q":"Huntington,+WV",
  "faqs":[
   ("Is Serene Med Spa in Huntington?","Our office is in Barboursville at 1 Chateau Grove Ln, just off I-64 exit 20 by the Huntington Mall &mdash; about 15 minutes from downtown Huntington and Marshall University. We serve all of Huntington, Cabell and Wayne counties, plus Ohio and Kentucky across the river."),
   ("How much is Botox in the Huntington area?","$10 per unit for Botox, Xeomin and Daxxify at Serene Barboursville ($3.99 per Dysport unit). Frown lines are typically 20 units, so about $200. We also match any published local price on injectables, and the consultation is free."),
   ("Who does the injections?","Board-certified physicians Dr. Shweta Arora and Dr. Robin Arora, and Stephanie Welker, FNP-BC. There are no rotating or part-time injectors."),
   ("Do you offer laser hair removal near Huntington?","Yes &mdash; with the Alma Soprano Ice Platinum, which is virtually painless and safe for all skin tones. Packages of six sessions are available; call for per-area pricing."),
   ("What is SKNLAB and is it different from HydraFacial?","SKNLAB is a six-handpiece facial that does everything a HydraFacial does (cleanse, exfoliate, extract, infuse) plus ultrasound, hot/cold therapy, electroporation, microcurrent and lymphatic drainage. Both are $150 at Serene Barboursville; your provider picks the sequence for your skin."),
   ("Is parking free and is it easy to find?","Yes. We&rsquo;re a street-level office with free parking right outside the door &mdash; no downtown Huntington parking garages."),
  ]},

 {"slug":"med-spa-ashland-ky","city":"Ashland","city_state":"Ashland, KY","also":["Russell, KY","Flatwoods, KY","Catlettsburg, KY","Greenup, KY"],
  "title":"Med Spa Near Ashland, KY | Physician Botox, Fillers & Laser",
  "desc":"Ashland, Russell & Flatwoods: a physician-led med spa 30 min away in Barboursville, WV. Botox $10/unit, Juvéderm fillers, laser hair removal, weight loss.",
  "h1":"A physician-led med spa for Ashland, Russell &amp; Flatwoods &mdash; 30 minutes up I-64",
  "hero":"Ashland patients used to choose between Lexington and Huntington for doctor-led aesthetics. Serene Med Spa is closer than both: board-certified physicians, published prices and a Tri-State price match, 30 minutes east off I-64 exit 20.",
  "drive":"About 30 minutes",
  "introh2":"Worth the drive from Boyd and Greenup counties",
  "introlead":"Ashland, Russell, Flatwoods and Catlettsburg patients tell us the same thing: they wanted a physician doing the injecting, not a franchise, and they didn&rsquo;t want to drive to Lexington for it. Serene is 30 minutes from Ashland via I-64.",
  "intro":"<p>Serene Med Spa is owned by Dr. Shweta Arora and Dr. Robin Arora, both board-certified physicians, who see every patient with Stephanie Welker, FNP-BC. We&rsquo;re an Allergan Platinum partner, a Merz preferred practice and an Alma, Cartessa and InMode device practice &mdash; Botox, the full Juv&eacute;derm family, Kybella, Sculptra, Soprano laser hair removal, Alma Hybrid resurfacing, SKNLAB and HydraFacial, medical weight loss and Bi&ouml;te hormone therapy, all in one office.</p><p>Every price is public: Botox $10/unit, filler $500/syringe, HydraFacial or SKNLAB $150, Kybella $600, weight-loss visits $149. See the <a href=\"/pricing/\">price list</a>. Because we publish our prices, we can also <a href=\"/#price-match\">match any published local price</a> on injectables &mdash; including Ashland and Huntington practices.</p><p>Getting here: US-23 north to I-64 east (or the 13th Street / Catlettsburg route to I-64), then east past Huntington to exit 20 at the Huntington Mall &mdash; about 30 minutes from Ashland, 35 from Russell and Flatwoods. Free parking is outside the door at 1 Chateau Grove Ln.</p>",
  "treatments":["botox","fillers","laser-hair-removal","weight-loss","kybella","hormone-optimization"],
  "directions":"<p><strong>From Ashland (about 25 miles):</strong> take US-23 North / US-60 to I-64 East (or cross at Catlettsburg to I-64), continue east past Huntington to exit 20 (Barboursville / Huntington Mall). We&rsquo;re at 1 Chateau Grove Ln just off US-60 &mdash; about 30 minutes.</p><p><strong>From Russell / Flatwoods / Greenup:</strong> US-23 South to I-64 East, about 35&ndash;40 minutes. <strong>From Catlettsburg:</strong> I-64 East, about 25 minutes.</p>",
  "origin_q":"Ashland,+KY",
  "faqs":[
   ("How far is Serene Med Spa from Ashland, KY?","About 25 miles &mdash; roughly 30 minutes via I-64 East to exit 20 in Barboursville, WV. Russell and Flatwoods are about 35 minutes; Catlettsburg about 25."),
   ("What does Botox cost compared with Ashland or Lexington?","$10 per unit at Serene Barboursville, injected by a board-certified physician, and we match any published local price on injectables. Most Ashland patients find that lower than what they were quoted in Lexington."),
   ("Can I get everything done in one trip from Kentucky?","Yes. Tell us you&rsquo;re driving in and we&rsquo;ll stack your consultation and treatment &mdash; Botox, filler, a facial or a laser session &mdash; into a single visit."),
   ("Do you offer medical weight loss for Kentucky patients?","Yes. Our physician-supervised semaglutide and tirzepatide program is $149 per visit with monthly check-ins. We can see you in person for the first visit and coordinate follow-ups around your drive."),
   ("Do you offer hormone therapy?","Yes &mdash; we&rsquo;re certified Bi&ouml;te providers offering pellet therapy for women ($405) and men (from $465), with lab work coordinated before your visit."),
   ("Is there a closer Serene location to Ashland?","Barboursville is the closest. We also have an office in Hudson, Ohio (near Akron) for patients who travel north."),
  ]},

 {"slug":"med-spa-ironton-oh","city":"Ironton","city_state":"Ironton, OH","also":["South Point, OH","Proctorville, OH","Chesapeake, OH","Coal Grove, OH","Burlington, OH"],
  "title":"Med Spa Near Ironton, OH | Botox $10/unit, Fillers & Laser",
  "desc":"Ironton, South Point, Proctorville & Chesapeake: a physician-led med spa 25–35 min away in Barboursville, WV. Botox $10/unit, Juvéderm, laser, SKNLAB.",
  "h1":"Lawrence County&rsquo;s physician-led med spa &mdash; just across the river in Barboursville",
  "hero":"From Ironton, South Point, Chesapeake and Proctorville, Serene Med Spa is the closest practice where board-certified physicians do the injecting and every price is published. Cross the bridge, take I-64 east a few miles to exit 20, and you&rsquo;re here.",
  "drive":"About 25&ndash;35 minutes",
  "introh2":"The med spa Lawrence County crosses the bridge for",
  "introlead":"Ohio&rsquo;s southern tip has very few physician-run aesthetic practices. Serene fills that gap from Barboursville, WV &mdash; 15 minutes from Proctorville, 20 from Chesapeake and South Point, and about 30 from Ironton.",
  "intro":"<p>Dr. Shweta Arora and Dr. Robin Arora, both board-certified physicians, own Serene and treat every patient alongside Stephanie Welker, FNP-BC. We&rsquo;re an Allergan Platinum partner, a Merz preferred practice and an Alma, Cartessa and InMode device practice: Botox and Juv&eacute;derm, Kybella and Sculptra, Soprano laser hair removal, Alma Hybrid resurfacing, Discovery Pico tattoo removal, SKNLAB and HydraFacial, weight loss and Bi&ouml;te hormone therapy.</p><p>Prices are public &mdash; Botox $10/unit, filler $500/syringe, HydraFacial or SKNLAB $150 &mdash; on our <a href=\"/pricing/\">price list</a>, and we <a href=\"/#price-match\">match any published local price</a> on injectables. Ohio patients pay the same as everyone else; there&rsquo;s no out-of-state difference.</p><p>From Proctorville take the East Huntington (31st Street) Bridge to I-64 east, a few miles to exit 20. From Chesapeake and South Point, US-52 east to the bridge, then I-64 east. From Ironton and Coal Grove, US-52 east about 20 miles to the bridge &mdash; about 30&ndash;35 minutes total. Free parking at the door at 1 Chateau Grove Ln.</p>",
  "treatments":["botox","fillers","laser-hair-removal","sknlab","laser-tattoo-removal","weight-loss"],
  "directions":"<p><strong>From Ironton (about 25 miles):</strong> take US-52 East through Coal Grove, South Point and Chesapeake to the East Huntington Bridge (OH-527 / 31st St), cross into West Virginia and take I-64 East a few miles to exit 20 (Barboursville / Huntington Mall). We&rsquo;re at 1 Chateau Grove Ln just off US-60 &mdash; about 30&ndash;35 minutes.</p><p><strong>From Proctorville:</strong> East Huntington Bridge to I-64 East, about 15 minutes. <strong>From Chesapeake / South Point:</strong> US-52 East to the bridge, then I-64 East, about 20 minutes.</p>",
  "origin_q":"Ironton,+OH",
  "faqs":[
   ("How far is Serene Med Spa from Ironton?","About 25 miles &mdash; roughly 30&ndash;35 minutes via US-52 East, the East Huntington Bridge and I-64 East to exit 20. Proctorville is about 15 minutes, Chesapeake and South Point about 20."),
   ("Do you charge Ohio patients the same prices?","Yes. Botox is $10 per unit, filler $500 per syringe and facials $150 for everyone, and our Tri-State price match applies to published prices from Ohio, Kentucky and West Virginia practices alike."),
   ("Are the injectors physicians?","Yes. Dr. Shweta Arora and Dr. Robin Arora are board-certified physicians who own the practice, joined by Stephanie Welker, FNP-BC."),
   ("Do you do laser tattoo removal near Ironton?","Yes &mdash; with the Discovery Pico Plus picosecond laser, for full removal or fading before a cover-up. Pricing is by tattoo size; the consultation is free."),
   ("Can I book a treatment directly instead of a consultation?","Yes. Use the Book button to choose Botox, filler, a facial or laser hair removal on our live calendar. First-time patients get a quick physician assessment at the start of that visit."),
   ("Do you see patients from Ashland and Huntington too?","Yes &mdash; we serve the whole Tri-State, including Ashland KY, Huntington WV and Lawrence County OH."),
  ]},

 {"slug":"med-spa-charleston-wv","city":"Charleston","city_state":"Charleston, WV","also":["South Charleston, WV","St. Albans, WV","Nitro, WV","Hurricane, WV","Teays Valley, WV"],
  "title":"Med Spa Near Charleston, WV | Physician Botox & Fillers",
  "desc":"Charleston, St. Albans & Hurricane: a physician-led med spa 45 min west on I-64. Botox $10/unit, Juvéderm, Alma Hybrid, laser hair removal, Ultherapy.",
  "h1":"A physician-led med spa for Charleston &amp; the Kanawha Valley &mdash; 45 minutes west on I-64",
  "hero":"Charleston has med spas. Serene is the one 45 minutes down I-64 where two board-certified physicians own the practice, do the injecting, publish every price and match any local quote &mdash; with the full Allergan, Alma and Ultherapy menu.",
  "drive":"About 45 minutes",
  "introh2":"Why Kanawha Valley patients drive to Serene",
  "introlead":"Patients from Charleston, South Charleston, St. Albans and Nitro make the I-64 trip for three reasons: a physician does the work, the prices are published (and matched), and the advanced treatments &mdash; Ultherapy, Alma Hybrid, Morpheus-style RF, Sculptra &mdash; are all in one place.",
  "intro":"<p>Serene Med Spa is owned by Dr. Shweta Arora (board-certified anesthesiology, certified in aesthetic medicine) and Dr. Robin Arora (board-certified internal medicine), who see every patient with Stephanie Welker, FNP-BC. We&rsquo;re an Allergan Platinum partner, a Merz Bronze preferred practice, an Ultherapy PRIME provider, and an Alma and Cartessa device practice.</p><p>That means the full menu: Botox ($10/unit), the whole Juv&eacute;derm family ($500/syringe), Kybella, Sculptra, Ultherapy (full face $2,200), Alma Hybrid laser resurfacing, Opus Plasma, Soprano laser hair removal, SKNLAB and HydraFacial ($150), medical weight loss and Bi&ouml;te hormones &mdash; with every price on our <a href=\"/pricing/\">price list</a> and a <a href=\"/#price-match\">Tri-State price match</a> on injectables.</p><p>The drive is a straight run: I-64 west from Charleston through Hurricane and Milton to exit 20 (Barboursville / Huntington Mall), about 45 minutes; from Hurricane or Teays Valley it&rsquo;s closer to 20. Tell us you&rsquo;re coming from the Kanawha Valley and we&rsquo;ll book your consultation and treatment together so one trip covers both. Free parking at the door.</p>",
  "treatments":["botox","fillers","alma-hybrid","laser-hair-removal","sculptra","hormone-optimization"],
  "directions":"<p><strong>From Charleston (about 45 miles):</strong> take I-64 West through Nitro, Hurricane and Milton to exit 20 (Barboursville / Huntington Mall). Follow US-60 toward the mall; we&rsquo;re at 1 Chateau Grove Ln &mdash; about 45 minutes.</p><p><strong>From St. Albans / Nitro:</strong> I-64 West, about 35 minutes. <strong>From Hurricane / Teays Valley:</strong> I-64 West or US-60 West, about 20 minutes.</p>",
  "origin_q":"Charleston,+WV",
  "faqs":[
   ("How far is Serene Med Spa from Charleston, WV?","About 45 miles west on I-64 &mdash; roughly 45 minutes to exit 20 in Barboursville. St. Albans and Nitro are about 35 minutes; Hurricane and Teays Valley about 20."),
   ("Why drive from Charleston instead of using a local med spa?","Two board-certified physicians own Serene and do the injecting; prices are published and matched; and advanced options like Ultherapy, Alma Hybrid and Sculptra are all in one office. Many Charleston patients also combine a visit with the Huntington Mall next door."),
   ("What does Botox cost?","$10 per unit for Botox, Xeomin and Daxxify ($3.99 per Dysport unit). Frown lines are typically 20 units. Consultations are free, and if a Charleston practice publishes a lower price on the same product, we match it."),
   ("Can I do the consultation and treatment in one trip?","Yes &mdash; that&rsquo;s how most of our Kanawha Valley patients book. Choose a free consultation online and note that you&rsquo;d like same-day treatment; we&rsquo;ll hold the time."),
   ("Do you offer Ultherapy near Charleston?","Yes. Serene is an Ultherapy PRIME provider; full face is $2,200, full face and neck $2,900, brow lift $850, performed by Dr. Shweta Arora."),
   ("Do you see patients from Hurricane, Teays Valley and Milton?","Yes &mdash; they&rsquo;re our closest Putnam County neighbors, 10&ndash;20 minutes away. We also serve Huntington, Ashland KY and Lawrence County OH."),
  ]},
]

# ---------- SEO pass 3 (Sep 2026): Putnam / eastern Cabell / Lawrence County OH service-area pages ----------
CITIES += [

 {"slug":"med-spa-milton-wv","city":"Milton","city_state":"Milton, WV","also":["Ona, WV","Culloden, WV","Salt Rock, WV","Glenwood, WV"],
  "title":"Med Spa Near Milton, WV | Botox $10/unit, Fillers & Laser",
  "desc":"Milton, Ona & Culloden: Serene Med Spa is 15 minutes west on US-60 or I-64 in Barboursville. Physician injectors, Botox $10/unit, Juvéderm $500, laser, weight loss.",
  "h1":"Milton&rsquo;s closest physician-led med spa &mdash; 15 minutes down US-60",
  "hero":"From Milton, Ona and Culloden, Serene Med Spa is the nearest practice where board-certified physicians do the injecting and every price is posted before you book. Take US-60 or I-64 west to exit 20 at the Huntington Mall and you&rsquo;re here in about 15 minutes.",
  "drive":"About 15 minutes",
  "introh2":"Why eastern Cabell County comes to Serene",
  "introlead":"Milton has grown fast, but there&rsquo;s still no physician-run aesthetic practice between Milton and Charleston. Serene fills that gap from Barboursville: 15 minutes from Milton, under 10 from Ona, and about 20 from Culloden.",
  "intro":"<p>Serene Med Spa is owned by Dr. Shweta Arora (board-certified anesthesiologist, certified in aesthetic medicine) and Dr. Robin Arora (board-certified internal medicine and nephrology), who see every patient alongside Stephanie Welker, FNP-BC. We&rsquo;re an Allergan Platinum partner, a Merz preferred practice, an Ultherapy PRIME provider and an Alma, Cartessa and InMode device practice &mdash; so Botox and the full Juv&eacute;derm family, Kybella and Sculptra, Morpheus8, Alma Hybrid resurfacing, Soprano laser hair removal, SKNLAB and HydraFacial, medical weight loss and Bi&ouml;te hormone therapy are all in one office.</p><p>Every price is public: Botox <strong>$10 per unit</strong>, filler <strong>$500 per syringe</strong> (three Juv&eacute;derm syringes $1,300), HydraFacial or SKNLAB <strong>$150</strong>, Morpheus8 $800 or three for $2,100. The full list is on our <a href=\"/pricing/\">pricing page</a>, and we <a href=\"/#price-match\">match any published local price</a> on injectables.</p><p>Getting here is the easy part. From Milton, US-60 West runs straight through Ona into Barboursville &mdash; about 12 miles. Or take I-64 West from exit 28 to exit 20 (Barboursville / Huntington Mall). We&rsquo;re at 1 Chateau Grove Ln, just off US-60 by the mall, with free parking outside the door. Many Milton patients pair a visit with a stop at the mall or Tanyard Station.</p>",
  "treatments":["botox","fillers","sknlab","laser-hair-removal","weight-loss","hormone-optimization"],
  "directions":"<p><strong>From Milton (about 12 miles):</strong> take US-60 West through Ona into Barboursville, or I-64 West from exit 28 to exit 20 (Barboursville / Huntington Mall). We&rsquo;re at 1 Chateau Grove Ln, just off US-60 near the mall &mdash; about 15 minutes.</p><p><strong>From Ona:</strong> US-60 West, under 10 minutes. <strong>From Culloden:</strong> US-60 West or I-64 West, about 20 minutes. <strong>From Salt Rock:</strong> WV-10 North to Barboursville, about 15 minutes.</p>",
  "origin_q":"Milton,+WV",
  "faqs":[
   ("How far is Serene Med Spa from Milton, WV?","About 12 miles &mdash; roughly 15 minutes west on US-60 or I-64 to exit 20 in Barboursville. Ona is under 10 minutes; Culloden and Salt Rock about 15&ndash;20."),
   ("Is there a med spa in Milton?","Not a physician-run one. Serene in Barboursville is the closest practice to Milton where board-certified physicians own the practice and perform the injectables, with every price published online."),
   ("How much is Botox near Milton?","$10 per unit for Botox, Xeomin and Daxxify at Serene Barboursville ($3.99 per Dysport unit). A frown-line treatment is typically 20 units, about $200, and the consultation is free."),
   ("Can I book a treatment on my first visit?","Yes. Use the Book button to pick Botox, filler, a facial or laser hair removal on our live calendar. First-time patients get a quick physician assessment at the start of that visit, and we can treat the same day if you&rsquo;re a candidate."),
   ("Do you offer medical weight loss and hormone therapy?","Yes. Physician-supervised weight-management visits are $149 per month, and we&rsquo;re certified Bi&ouml;te providers for pellet hormone therapy (women $405, men from $465), with labs coordinated before your visit."),
   ("Is parking easy?","Yes &mdash; we&rsquo;re a street-level office with free parking right outside the door at 1 Chateau Grove Ln."),
  ]},

 {"slug":"med-spa-hurricane-wv","city":"Hurricane","city_state":"Hurricane, WV","also":["Teays Valley, WV","Scott Depot, WV","Winfield, WV","Culloden, WV","Poca, WV"],
  "title":"Med Spa Near Hurricane & Teays Valley, WV | Physician Botox",
  "desc":"Hurricane, Teays Valley, Scott Depot & Winfield: a physician-led med spa 20 min west on I-64 in Barboursville. Botox $10/unit, Juvéderm, Morpheus8, Ultherapy, laser.",
  "h1":"Putnam County&rsquo;s physician-led med spa &mdash; 20 minutes west on I-64",
  "hero":"Hurricane and Teays Valley patients have two choices for doctor-led aesthetics: drive east to Charleston, or 20 minutes west to Serene in Barboursville, where board-certified physicians own the practice, do the injecting, publish every price and match any local quote.",
  "drive":"About 20 minutes",
  "introh2":"Why Teays Valley drives west instead of east",
  "introlead":"From Hurricane, Scott Depot and Winfield, Barboursville is as close as Charleston &mdash; and Serene is one of the very few practices in the region where the person holding the syringe is a board-certified physician.",
  "intro":"<p>Dr. Shweta Arora (board-certified anesthesiology, certified in aesthetic medicine) and Dr. Robin Arora (board-certified internal medicine) own Serene and treat every patient with Stephanie Welker, FNP-BC. We&rsquo;re an Allergan Platinum partner, a Merz preferred practice, an Ultherapy PRIME provider and an Alma, Cartessa and InMode device practice. That means the full menu under one roof: Botox and the whole Juv&eacute;derm family, Kybella and Sculptra, Morpheus8, Ultherapy, Alma Hybrid CO&sup2; resurfacing, Soprano laser hair removal, SKNLAB and HydraFacial, medical weight loss and Bi&ouml;te hormone pellets.</p><p>Prices are published and matched: Botox <strong>$10 per unit</strong>, filler <strong>$500 per syringe</strong>, Morpheus8 $800 (three for $2,100), Ultherapy full face $2,200, facials $150 &mdash; every number is on our <a href=\"/pricing/\">price list</a>, and the <a href=\"/#price-match\">Tri-State price match</a> covers injectables from Charleston and Huntington practices alike.</p><p>The drive is a straight shot: I-64 West from Hurricane (exit 34) or Teays Valley to exit 20 (Barboursville / Huntington Mall), about 14 miles from Hurricane and 20 from Scott Depot. We&rsquo;re at 1 Chateau Grove Ln just off US-60 by the mall, with free parking at the door. Tell us you&rsquo;re coming from Putnam County and we&rsquo;ll book your consultation and treatment together.</p>",
  "treatments":["botox","fillers","alma-hybrid","laser-hair-removal","sculptra","weight-loss"],
  "directions":"<p><strong>From Hurricane (about 14 miles):</strong> take I-64 West to exit 20 (Barboursville / Huntington Mall), then follow US-60 toward the mall. We&rsquo;re at 1 Chateau Grove Ln &mdash; about 18&ndash;20 minutes. US-60 West through Culloden and Milton is a slower, scenic alternative.</p><p><strong>From Teays Valley / Scott Depot:</strong> I-64 West, about 20&ndash;25 minutes. <strong>From Winfield or Poca:</strong> WV-34 or WV-62 to I-64 West, about 25&ndash;30 minutes.</p>",
  "origin_q":"Hurricane,+WV",
  "faqs":[
   ("How far is Serene Med Spa from Hurricane, WV?","About 14 miles &mdash; roughly 20 minutes west on I-64 to exit 20 in Barboursville. Teays Valley and Scott Depot are 20&ndash;25 minutes; Winfield about 25&ndash;30."),
   ("Why not just go to Charleston?","For most of Putnam County, Barboursville is the same drive or shorter. At Serene, two board-certified physicians own the practice and do the injecting, prices are published and matched, and Ultherapy, Morpheus8, Alma Hybrid and Sculptra are all in one office."),
   ("How much is Botox near Teays Valley?","$10 per unit for Botox, Xeomin and Daxxify at Serene Barboursville ($3.99 per Dysport unit). Frown lines are typically 20 units, so about $200. We match any published local price on injectables, and the consultation is free."),
   ("Do you offer Ultherapy and Morpheus8?","Yes. We&rsquo;re an Ultherapy PRIME provider (full face $2,200, full face and neck $2,900) and offer Morpheus8 RF microneedling at $800 per treatment or three for $2,100."),
   ("Can I get a consultation and treatment in one trip?","Yes. Tell us you&rsquo;re driving in from Putnam County and we&rsquo;ll schedule the consultation and treatment back to back &mdash; Botox, filler, a facial or a laser session can usually be done the same day."),
   ("Where do I park?","Free parking is right outside the door at 1 Chateau Grove Ln, a street-level office just off US-60 near the Huntington Mall."),
  ]},

 {"slug":"med-spa-proctorville-oh","city":"Proctorville","city_state":"Proctorville, OH","also":["South Point, OH","Chesapeake, OH","Rome Township, OH","Burlington, OH","Athalia, OH"],
  "title":"Med Spa Near Proctorville & South Point, OH | Botox $10/unit",
  "desc":"Proctorville, South Point & Chesapeake: a physician-led med spa just across the East Huntington Bridge in Barboursville, WV. Botox $10/unit, Juvéderm $500, laser, SKNLAB.",
  "h1":"The physician-led med spa just across the bridge from Proctorville",
  "hero":"From Proctorville, Rome Township and South Point, Serene Med Spa is 15&ndash;20 minutes away: over the East Huntington Bridge, a few miles east on I-64, and off at exit 20. Board-certified physicians do the injecting, every price is published, and Ohio patients pay exactly what everyone else does.",
  "drive":"About 15&ndash;20 minutes",
  "introh2":"Closer than Ironton, closer than Ashland",
  "introlead":"Eastern Lawrence County sits directly across the Ohio River from Barboursville and Huntington. For Proctorville, Rome Township, Chesapeake and South Point, Serene is the nearest practice owned and run by physicians &mdash; and the only one with prices posted online.",
  "intro":"<p>Dr. Shweta Arora and Dr. Robin Arora, both board-certified physicians, own Serene and treat every patient alongside Stephanie Welker, FNP-BC. We&rsquo;re an Allergan Platinum partner, a Merz preferred practice, an Ultherapy PRIME provider and an Alma, Cartessa and InMode device practice: Botox and Juv&eacute;derm, Kybella and Sculptra, Morpheus8, Soprano laser hair removal, Alma Hybrid resurfacing, Discovery Pico tattoo removal, SKNLAB and HydraFacial, medical weight loss and Bi&ouml;te hormone therapy.</p><p>Prices are public &mdash; Botox <strong>$10 per unit</strong>, filler <strong>$500 per syringe</strong> (three Juv&eacute;derm syringes $1,300), HydraFacial or SKNLAB <strong>$150</strong> &mdash; on our <a href=\"/pricing/\">price list</a>, and we <a href=\"/#price-match\">match any published local price</a> on injectables, including Ohio and Kentucky practices. There&rsquo;s no out-of-state difference.</p><p>From Proctorville, cross the East Huntington (31st Street) Bridge, pick up I-64 East and take exit 20 (Barboursville / Huntington Mall) &mdash; about 12 miles. From Chesapeake, the Robert C. Byrd Bridge into downtown Huntington then I-64 East is about 20 minutes; from South Point, US-52 East to either bridge is 20&ndash;25. Free parking at the door at 1 Chateau Grove Ln.</p>",
  "treatments":["botox","fillers","sknlab","laser-hair-removal","laser-tattoo-removal","weight-loss"],
  "directions":"<p><strong>From Proctorville / Rome Township (about 12 miles):</strong> take OH-7 to the East Huntington Bridge (31st Street), cross into West Virginia, follow the signs to I-64 East and take exit 20 (Barboursville / Huntington Mall). We&rsquo;re at 1 Chateau Grove Ln just off US-60 &mdash; about 15 minutes.</p><p><strong>From Chesapeake:</strong> the Robert C. Byrd Bridge into Huntington, then I-64 East to exit 20, about 20 minutes. <strong>From South Point / Burlington:</strong> US-52 East to the East Huntington Bridge, then I-64 East, about 20&ndash;25 minutes.</p>",
  "origin_q":"Proctorville,+OH",
  "faqs":[
   ("How far is Serene Med Spa from Proctorville, OH?","About 12 miles &mdash; roughly 15 minutes via the East Huntington Bridge and I-64 East to exit 20 in Barboursville. Chesapeake is about 20 minutes; South Point and Burlington 20&ndash;25."),
   ("Do Ohio patients pay the same prices?","Yes. Botox is $10 per unit, filler $500 per syringe and facials $150 for everyone, and our Tri-State price match applies to published prices from Ohio, Kentucky and West Virginia practices alike."),
   ("Who does the injections?","Board-certified physicians Dr. Shweta Arora and Dr. Robin Arora, and Stephanie Welker, FNP-BC. There are no rotating or part-time injectors."),
   ("Do you offer laser hair removal and tattoo removal?","Yes &mdash; laser hair removal with the Alma Soprano Ice Platinum (virtually painless, safe for all skin tones) and tattoo removal with the Discovery Pico Plus picosecond laser. Consultations are free."),
   ("Can I book a treatment directly instead of a consultation?","Yes. Use the Book button to choose Botox, filler, a facial or laser hair removal on our live calendar. First-time patients get a quick physician assessment at the start of that visit."),
   ("Is Serene closer than the Ironton or Ashland options?","For Proctorville, Rome Township and Chesapeake, yes &mdash; Barboursville is 15&ndash;20 minutes. We also see many patients from Ironton, South Point and Ashland, KY."),
  ]},
]
